# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run. ** Replace with your directory.
CMAKE_SOURCE_DIR = /Users/vasilis/Documents/Projects/emacs_gpp/reaction-diffusion

# The top-level build directory on which CMake was run. ** Replace with your directory.
CMAKE_BINARY_DIR = /Users/vasilis/Documents/Projects/emacs_gpp/reaction-diffusion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target. ** Replace with your directory.
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vasilis/Documents/Projects/emacs_gpp/reaction-diffusion/CMakeFiles /Users/vasilis/Documents/Projects/emacs_gpp/reaction-diffusion/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vasilis/Documents/Projects/emacs_gpp/reaction-diffusion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tiny

# Build rule for target.
tiny: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiny
.PHONY : tiny

# fast build rule for target.
tiny/fast:
	$(MAKE) -f CMakeFiles/tiny.dir/build.make CMakeFiles/tiny.dir/build
.PHONY : tiny/fast

#=============================================================================
# Target rules for targets named report

# Build rule for target.
report: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 report
.PHONY : report

# fast build rule for target.
report/fast:
	$(MAKE) -f CMakeFiles/report.dir/build.make CMakeFiles/report.dir/build
.PHONY : report/fast

#=============================================================================
# Target rules for targets named perf

# Build rule for target.
perf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perf
.PHONY : perf

# fast build rule for target.
perf/fast:
	$(MAKE) -f CMakeFiles/perf.dir/build.make CMakeFiles/perf.dir/build
.PHONY : perf/fast

#=============================================================================
# Target rules for targets named valgrind

# Build rule for target.
valgrind: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind
.PHONY : valgrind

# fast build rule for target.
valgrind/fast:
	$(MAKE) -f CMakeFiles/valgrind.dir/build.make CMakeFiles/valgrind.dir/build
.PHONY : valgrind/fast

#=============================================================================
# Target rules for targets named BufferLib

# Build rule for target.
BufferLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BufferLib
.PHONY : BufferLib

# fast build rule for target.
BufferLib/fast:
	$(MAKE) -f CMakeFiles/BufferLib.dir/build.make CMakeFiles/BufferLib.dir/build
.PHONY : BufferLib/fast

#=============================================================================
# Target rules for targets named reaction-diffusion

# Build rule for target.
reaction-diffusion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reaction-diffusion
.PHONY : reaction-diffusion

# fast build rule for target.
reaction-diffusion/fast:
	$(MAKE) -f CMakeFiles/reaction-diffusion.dir/build.make CMakeFiles/reaction-diffusion.dir/build
.PHONY : reaction-diffusion/fast

#=============================================================================
# Target rules for targets named DisplayLib

# Build rule for target.
DisplayLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DisplayLib
.PHONY : DisplayLib

# fast build rule for target.
DisplayLib/fast:
	$(MAKE) -f CMakeFiles/DisplayLib.dir/build.make CMakeFiles/DisplayLib.dir/build
.PHONY : DisplayLib/fast

#=============================================================================
# Target rules for targets named AsmLib

# Build rule for target.
AsmLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsmLib
.PHONY : AsmLib

# fast build rule for target.
AsmLib/fast:
	$(MAKE) -f CMakeFiles/AsmLib.dir/build.make CMakeFiles/AsmLib.dir/build
.PHONY : AsmLib/fast

src/buffer.o: src/buffer.cpp.o

.PHONY : src/buffer.o

# target to build an object file
src/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/BufferLib.dir/build.make CMakeFiles/BufferLib.dir/src/buffer.cpp.o
.PHONY : src/buffer.cpp.o

src/buffer.i: src/buffer.cpp.i

.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/BufferLib.dir/build.make CMakeFiles/BufferLib.dir/src/buffer.cpp.i
.PHONY : src/buffer.cpp.i

src/buffer.s: src/buffer.cpp.s

.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/BufferLib.dir/build.make CMakeFiles/BufferLib.dir/src/buffer.cpp.s
.PHONY : src/buffer.cpp.s

src/display.o: src/display.cpp.o

.PHONY : src/display.o

# target to build an object file
src/display.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayLib.dir/build.make CMakeFiles/DisplayLib.dir/src/display.cpp.o
.PHONY : src/display.cpp.o

src/display.i: src/display.cpp.i

.PHONY : src/display.i

# target to preprocess a source file
src/display.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayLib.dir/build.make CMakeFiles/DisplayLib.dir/src/display.cpp.i
.PHONY : src/display.cpp.i

src/display.s: src/display.cpp.s

.PHONY : src/display.s

# target to generate assembly for a file
src/display.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayLib.dir/build.make CMakeFiles/DisplayLib.dir/src/display.cpp.s
.PHONY : src/display.cpp.s

src/laplace.o: src/laplace.nasm.o

.PHONY : src/laplace.o

# target to build an object file
src/laplace.nasm.o:
	$(MAKE) -f CMakeFiles/AsmLib.dir/build.make CMakeFiles/AsmLib.dir/src/laplace.nasm.o
.PHONY : src/laplace.nasm.o

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/reaction-diffusion.dir/build.make CMakeFiles/reaction-diffusion.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/reaction-diffusion.dir/build.make CMakeFiles/reaction-diffusion.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/reaction-diffusion.dir/build.make CMakeFiles/reaction-diffusion.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... tiny"
	@echo "... report"
	@echo "... perf"
	@echo "... valgrind"
	@echo "... BufferLib"
	@echo "... reaction-diffusion"
	@echo "... rebuild_cache"
	@echo "... DisplayLib"
	@echo "... AsmLib"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/display.o"
	@echo "... src/display.i"
	@echo "... src/display.s"
	@echo "... src/laplace.o"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
